baseURL: https://savannahostrowski.com/
languageCode: en-us
title: Savannah Bailey
theme: github.com/adityatelange/hugo-PaperMod

params:
  env: production
  description: >
      Python Core Developer

  homeInfoParams:
    title: "HeyðŸ‘‹! I'm Savannah."
    subtitle: "nÃ©e Savannah Ostrowski"
    description: >
      Python Core Developer

  socialIcons:
    - name: github
      url: 'https://github.com/savannahostrowski'
    - name: bluesky
      url: 'https://bsky.app/profile/savannah.dev'
    - name: linkedin
      url: 'https://linkedin.com/in/savannahostrowski'
    - name: youtube
      url: 'https://youtube.com/playlist?list=PLq8oMtzrBmrgGXsW1theGfIwDu8ShD5hp&si=v49B7de8avnd-Rvx'

  showReadingTime: true
  showPostNavLinks: true
  showCodeCopyButtons: true
  showFullTextInRSS: true
  showRssButtonInSectionTermList: true
  showWordCount: true
  showToc: true


  schema:
    publisherType: Person

menu:
  main:
    - name: About
      url: /
      weight: 5
    - name: Archive
      url: /archives
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON
